# Generated by Django 2.2.6 on 2019-10-17 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.CharField(choices=[('p', 'Platillo'), ('b', 'Bebida')], default='p', help_text='Categoria del Producto', max_length=1)),
                ('imagen', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('precio', models.CharField(max_length=200)),
                ('pedido', models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Pedido')),
                ('producto', models.ForeignKey(db_column='producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Producto', verbose_name='Productos')),
            ],
        ),
    ]
