# Generated by Django 2.2.6 on 2019-10-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.CharField(blank=True, choices=[('p', 'Platillo'), ('b', 'bebida')], default='p', help_text='Categoria del Producto', max_length=1)),
                ('imagen', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
