# Generated by Django 2.2.6 on 2019-10-10 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('p', 'Platillo'), ('b', 'Bebida')], default='p', help_text='Categoria del Producto', max_length=1),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('pedido', models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Pedido')),
                ('producto', models.ForeignKey(db_column='producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Producto', verbose_name='Productos')),
            ],
        ),
    ]
