# Generated by Django 2.2.6 on 2019-10-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20191010_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
