# Generated by Django 2.2.6 on 2019-10-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20191010_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='base',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
