# Generated by Django 2.2.6 on 2019-10-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20191013_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio',
        ),
    ]
