# Generated by Django 2.2.6 on 2019-10-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20191015_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Pedido'),
        ),
    ]
