# Generated by Django 2.2.6 on 2019-10-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20191016_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
