# Generated by Django 2.2.6 on 2019-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20191016_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.CharField(max_length=100),
        ),
    ]
