# Generated by Django 2.2.6 on 2019-10-17 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20191016_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=10)),
                ('pedido', models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Pedido')),
            ],
        ),
    ]
