# Generated by Django 2.2.6 on 2019-10-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_auto_20191017_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
