# Generated by Django 2.2.6 on 2019-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_auto_20191023_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default='Consumidor Final', max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nit',
            field=models.CharField(default='C.F', max_length=10),
        ),
    ]
